---
version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    network_mode: "host"
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
    volumes:
      - /app/unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp 
      - 8843:8843 
      - 8880:8880 
      - 6789:6789 
      - 5514:5514/udp 
    restart: always
