apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory 
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        cloudflare:
          email: bajada.victor@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token